### ISSUE TITLE
Dll's missing

### ISSUE THREAD

**Issue by dutchkiller2000** [exp111/TotallyAccurateBattlegroundsStuff#1]
i tried the build this project but it says that the dll are missing, were can i find these dll's?

**Comment by exp111** [comment]
How do people even find my repos?
You have to reference the game assemblies. These should be found in the game folder (they compiled these with the game executable but afaik reversed it again).

**Comment by dutchkiller2000** [comment]
i just wanted to experiment with the game and thanks for the reply

**Comment by exp111** [comment]
@dutchkiller2000 if you want to learn something about mono injection watch [this video](https://www.youtube.com/watch?v=9f5u_2NIIuk) (~40min).
